defaults:
  scan_type: quick
  report_format: html
  timeout: 10
  
nvd:
  api_key: ""
  rate_limit: 5
  cache_ttl: 3600  # ← New but optional
  
plugins:
  web:
    sql_test_payloads: ["' OR '1'='1", "UNION SELECT"]
    xss_test_payloads: ["<script>alert(1)</script>"]
